### ISSUE TITLE
many issues (skip links top of page and I don't have a favicon )

### ISSUE THREAD

**Issue by Jessica3860** [Jessica3860/web-design-2-independent-project#2]
@wendywarren

I have a few issues 
1.  I don't know how to rid the white gap my skip links have coursed. 
2. Markbot doesn't like that I don't have a 48 x 48 favicon.ico, but the website didn't even have 48 as an option.
3. I don't know what markbot is wanting from me 
![image](https://user-images.githubusercontent.com/83955882/163696468-9e07dd4c-9928-445f-9f1c-6ae6a42040fb.png)
4. also accessibility issues 
![image](https://user-images.githubusercontent.com/83955882/163695057-4a380954-b522-405c-8d6e-a5930f695cc9.png)

**Comment by wendywarren** [comment]
Hi @Jessica3860,

Are you still experiencing your issues? If so, let me know and I can arrange to chat with you over zoom tomorrow after 11am.

The contentinfo is referring to the role associated with your footer. 

Don't worry about the form elements must have labels issue.

Thanks,
Wendy

**Comment by Jessica3860** [comment]
hi @wendywarren

I am still having issues. I am going to try and figure out/ fix what is left tonight. though I think it would be good to arrange for a zoom call tomorrow just in case.

thank you, 
-Jessica

p.s any time after 11am works for me. I have nothing on tomorrow.

**Comment by wendywarren** [comment]
Perfect! I'm available at 1:30. :) I'll send you a zoom link over here shortly before we meet.

**Comment by wendywarren** [comment]
Hi @Jessica3860,

Here is the [zoom link](https://algonquincollege.zoom.us/j/93484990003?pwd=RFo5YlhqR2FhQ1JGaVhja3laUjM2UT09) for 1:30. Let me know if you have any issues accessing.

Thanks,
Wendy

**Comment by Jessica3860** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
